services: 
    sqlserver:
        container_name: RoundRobinTournament-SQLServer
        build:
            dockerfile: sqlserver-fulltext.Dockerfile
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "Some4Complex#Password"
            ACCEPT_EULA: "Y"
        volumes:
            - db-vol:/var/opt/mssql
        networks:
            - db-network
volumes:
    # sur linux il crée un dossier dans /var/lib/docker/volumes/db-vol
    db-vol:

networks:
    db-network:
        driver: bridge


# docker-compose -p round_robin_tournament up -d
# docker-compose -p round_robin_tournament down
