services: 
#    Not working yet
    api-dev:
        container_name: PokemonBattleAPI
        image: mcr.microsoft.com/dotnet/sdk:8.0
        command: bash -c "dotnet restore && dotnet watch run -e RESTART_PROMPT=never"
        working_dir:
            /app/PokemonBattleAPI
        ports:
            - "5239:5239"
        volumes:
            - ../:/app
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        depends_on:
            - sqlserver
        networks:
            - db-network

    sqlserver:
        container_name: PokemonBattleAPI-SQLServer
        build:
            dockerfile: sqlserver-fulltext.Dockerfile
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "Some4Complex#Password"
            ACCEPT_EULA: "Y"
        volumes:
            - db-vol:/var/opt/mssql
        networks:
            - db-network
volumes:
    # sur linux il crée un dossier dans /var/lib/docker/volumes/db-vol
    db-vol:

networks:
    db-network:
        driver: bridge


# docker-compose -p pokemon_battle_api up -d
# docker-compose -p pokemon_battle_api down
